In [1]:
import numpy as np

#### Create an array from existing data

How to create an array from existing data\
This section covers `slicing and indexing`,\
`np.vstack()`, `np.hstack()`, `np.hsplit()`, `.view()`, `copy()`

In [3]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr = a[3:8]
arr

array([4, 5, 6, 7, 8])

`hstack` & `vstack`

In [5]:
a1 = np.array([[1, 1],
               [2, 2]]) 
a2 = np.array([[3, 3],
               [4, 4]])

In [7]:
b = np.hstack((a1,a2))
b

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [8]:
b = np.vstack((a1,a2))
b

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

`hsplit`

In [17]:
x = np.arange(1, 25)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [18]:
np.hsplit(x, 3)

[array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21, 22, 23, 24])]

In [15]:
x = np.arange(1, 25)
x = x.reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [16]:
# Split into 3 Chunks
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [21]:
a = np.hsplit(x, (3, 4))
a

[array([1, 2, 3]),
 array([4]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24])]

`.view()` Method

In [23]:
x.view()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

`.copy()` Method

In [24]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b = a.copy()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])