In [7]:
import numpy as np

Create an array filled with 0’s:

In [8]:
# np.zeros(Number of Values)
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

Create an array filled with 1’s:

In [9]:
# np.ones(Number of Values)
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

Create an Empty array:

In [16]:
# np.empty(Number of Values)
np.empty(4)

array([2.12199579e-314, 4.67296746e-307, 4.78255545e-321, 9.61264094e-312])

Create an array with a range of elements:

In [18]:
np.arange(4)
# 0->4

array([0, 1, 2, 3])

first number, last number, and the step size

In [19]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

Create an array with values that are spaced linearly in a specified interval:

In [22]:
# Starting , Ending , Total Values
np.linspace(5,25,num=20)

array([ 5.        ,  6.05263158,  7.10526316,  8.15789474,  9.21052632,
       10.26315789, 11.31578947, 12.36842105, 13.42105263, 14.47368421,
       15.52631579, 16.57894737, 17.63157895, 18.68421053, 19.73684211,
       20.78947368, 21.84210526, 22.89473684, 23.94736842, 25.        ])

Specifying your data type

In [25]:
np.linspace(5,25,num=20,dtype=np.int64)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 25], dtype=int64)

In [26]:
np.ones(2, dtype=np.int64)

array([1, 1], dtype=int64)