In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a[0]

1

In [4]:
#  the array is mutable. we can change values after creating
a[1] = 200
a

array([  1, 200,   3,   4,   5,   6])

In [5]:
# Starting se 3 tak
a[:3]

array([  1, 200,   3])

In [6]:
b = a[3:]
b

array([4, 5, 6])

In [7]:
b[0] = 500
b

array([500,   5,   6])

In [8]:
# orignal Array also changed
a

array([  1, 200,   3, 500,   5,   6])

2D Array

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
a[0]

array([1, 2, 3, 4])

In [11]:
a[0,2]

3

In [12]:
a[0][2]

3

In [13]:
a.ndim
# 2D Array

2

In [14]:
a.shape
# 3 Rows and 4 Columns

(3, 4)

In [15]:
a.size
# 12 Values

12

In [16]:
# Array can contain values of only 1 Data Type - Homogenous
a.dtype

dtype('int32')