In [1]:
import numpy as np

Basic array operations

In [6]:
a = np.array([1,2,3,4,5])
b = np.ones(5,dtype=np.int64)
b

array([1, 1, 1, 1, 1], dtype=int64)

In [8]:
a + b

array([2, 3, 4, 5, 6], dtype=int64)

In [9]:
a-b

array([0, 1, 2, 3, 4], dtype=int64)

In [10]:
a*b

array([1, 2, 3, 4, 5], dtype=int64)

In [11]:
a/b

array([1., 2., 3., 4., 5.])

`sum()`

In [13]:
a = np.array([1, 2, 3, 4])
a.sum()

10

`max()` and `min()`

In [19]:
a.min()

1

In [18]:
a.max()

4

To add the rows or the columns in a 2D array, you would specify the axis.

In [15]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [16]:
b.sum(axis=0) #Rows

array([3, 3])

In [17]:
b.sum(axis=1) #Column

array([2, 4])