In [26]:
import numpy as np

Convert a 1D array into a 2D array and 3D

In [27]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [28]:
# Convert to 2D Array - Row
b = a[np.newaxis,:]
print(b)
print(b.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [29]:
# Column
c = a[:,np.newaxis]
print(c)
print(c.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [30]:
# Convert to 3D Array
d = b[np.newaxis,:]
print(d)
print(d.shape)

[[[1 2 3 4 5 6]]]
(1, 1, 6)


You can also expand an array by inserting a new axis at a specified position with \
 `np.expand_dims`.

In [31]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [32]:
b = np.expand_dims(a,axis=1)
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [33]:
c = np.expand_dims(a,axis=0)
print(c)
print(c.shape)

[[1 2 3 4 5 6]]
(1, 6)
