In [1]:
import numpy as np

Indexing and slicing

In [4]:
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [5]:
data[0]

1

In [7]:
data[0:2]

array([1, 2])

In [8]:
data[2:]

array([3, 4, 5])

In [9]:
data[-2:]

array([4, 5])

In [11]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
a[0]

array([1, 2, 3, 4])

In [13]:
a[2]

array([ 9, 10, 11, 12])

In [14]:
a[0,2]

3

In [16]:
a[2][2]

11

Condition

In [17]:
a[a<5]

array([1, 2, 3, 4])

In [18]:
a[a>6]

array([ 7,  8,  9, 10, 11, 12])

In [22]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
a[(a<5)&(a%2==0)]

array([2, 4])

In [23]:
a[(a<5)|(a==5)]

array([1, 2, 3, 4, 5])

You can also use `np.nonzero()` to select elements or indices from an array.

In [24]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [26]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))
