In [1]:
import numpy as np

Creating matrices

In [2]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
a[0]

(array([1, 2]), 'Value:', 2)

In [7]:
a[0,1]

2

In [9]:
print(a.max())
print(a.min())
print(a.sum())

6
1
21


In [11]:
print(a.max(axis=1))
print(a.max(axis=0))

[2 4 6]
[5 6]


Generate Random Numbers

In [18]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

array([0.39763017, 0.82427626, 0.60304315])

In [19]:
rng.integers(5, size=(2, 4)) 

array([[4, 2, 0, 2],
       [2, 0, 1, 2]], dtype=int64)

Transposing and reshaping a matrix

In [30]:
data = np.matrix([[1,2,3],[4,5,6]])
data

matrix([[1, 2, 3],
        [4, 5, 6]])

In [31]:
data.transpose()

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [33]:
data.T

matrix([[1, 4],
        [2, 5],
        [3, 6]])

How to reverse an array/Matrix

In [34]:
np.flip(data)

matrix([[6, 5, 4],
        [3, 2, 1]])

In [36]:
np.flip(data,axis=0) #Rows

matrix([[4, 5, 6],
        [1, 2, 3]])

In [35]:
np.flip(data,axis=1) #Columns

matrix([[3, 2, 1],
        [6, 5, 4]])

Reshaping and flattening multidimensional arrays

This section covers .flatten(), ravel()

In [37]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

You can use `flatten` to flatten your array into a 1D array.

In [41]:
x.flatten() # Changes Cannot Effect on Parent Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
x.ravel() # Changes Can Effect on Parent Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])