In [9]:
import numpy as np

Reshape an array - `arr.reshape()`

In [10]:
a = np.arange(6)
print(a)
print(a.shape)

[0 1 2 3 4 5]
(6,)


In [11]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])