In [15]:
import numpy as np

Sorting an array is simple with `np.sort()`

In [16]:
arr = np.array([2,10,6,12,4,3,9,7,8,1,5,11])
print(arr)
print("Sorting",np.sort(arr))

[ 2 10  6 12  4  3  9  7  8  1  5 11]
Sorting [ 1  2  3  4  5  6  7  8  9 10 11 12]


The argsort function returns the indices that would sort an array. - `np.argsort(arr)` 

In [17]:
print("Shows the Orignal Index - Before Sorting Index\n",np.argsort(arr))

Shows the Orignal Index - Before Sorting Index
 [ 9  0  5  4 10  2  7  8  6  1 11  3]


The `np.searchsorted` function finds the indices where elements\
should be inserted to maintain order in a sorted array.

In [18]:
np.searchsorted([11,12,13,14,15], 13)

2

In [19]:
np.searchsorted([11,12,13,14,15], [13,16,10])

array([2, 5, 0], dtype=int64)

You can concatenate Array with `np.concatenate()`.

In [20]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [21]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [23]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[7,8]])

In [26]:
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])