In [1]:
import numpy as np

How to get unique items and counts

In [2]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

Unique Values

In [ ]:
unique_values = np.unique(a)
print(unique_values)

Indexes of Unique Values

In [3]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


Occurrence count

In [4]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


For 2D Array

In [6]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [7]:
unique_values = np.unique(a)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Unique Rows

In [8]:
unique_rows = np.unique(a, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


index position of Unique Values

In [9]:
unique_rows, indices = np.unique(
     a, axis=0, return_index=True)
print(indices)

[0 1 2]


Occurrence_count

In [11]:
unique_rows, occurrence_count= np.unique(
     a, axis=0, return_counts=True)
print(occurrence_count)

[2 1 1]
